spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dilip_reactive
---
spring:
  profiles: nonprod
  data:
    mongodb:
      host: 192.168.1.41
      port: 27017
      database: dilip_reactive
---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dilip_reactive

